### ISSUE TITLE
Exponentiation for rational numbers fails incorrectly

### ISSUE THREAD

**Issue by triska** [SWI-Prolog/packages-clpqr#1]
We have:

<pre>
%?- { (1 rdiv 2)*(1 rdiv 2)  = D }.
%@ D = 1 rdiv 4.
</pre>

but:

<pre>
%?- { (1 rdiv 2)^2  = D }.
%@ <b>false</b>.
</pre>

even though exponentiation for _integers_ works exactly as expected:

<pre>
%?- { 2^2  = D }.
%@ <b>D = 4</b>.
</pre>

I'm filing this as one of the issues I need to fix either in CLP(Q) or its reimplementation.

See the [**roadmap&nbsp;item**](https://github.com/SWI-Prolog/roadmap/issues/27).

**Comment by JanWielemaker** [comment]
Fixed with Issue #185

**Comment by ghost** [comment]
Hi Markus, what is your opinion on test cases and behaviour?
See also here: https://github.com/SWI-Prolog/swipl-devel/issues/185#issuecomment-312603630

**Comment by triska** [comment]
*Is there a floating point number?* &rightarrow; Please make it go away!

This concrete case is fixed, but https://github.com/SWI-Prolog/packages-clpqr/issues/2 remains.
