### ISSUE TITLE
Exponentiation for rational numbers fails incorrectly

### ISSUE THREAD

**Issue by triska** [SWI-Prolog/packages-clpqr#2]
We have, with SICStus Prolog:

<pre>
| ?- { X = 3/2, Y = X^(-1) }.
X = 3/2,
Y = 2/3 ? ;
no
</pre>

and with SWI-Prolog:

<pre>
?- { X = 3/2, Y = X^(-1) }.
<b>false.</b>
</pre>

I'm filing this as one of the issues I need to fix either in CLP(Q) or its reimplementation.

See the [**roadmap item**](https://github.com/SWI-Prolog/roadmap/issues/27).

**Comment by JanWielemaker** [comment]
This one is also fixed with the fixed rational division.
